channels:
  - currentCSV: ibm-monitoring-prometheus-operator-ext.v1.9.3
    name: stable-v1
  - currentCSV: ibm-monitoring-prometheus-operator-ext.v1.9.4
    name: beta
  - currentCSV: ibm-monitoring-prometheus-operator-ext.v1.9.5
    name: dev
  - currentCSV: ibm-monitoring-prometheus-operator-ext.v1.9.6
    name: v3
defaultChannel: stable-v1
packageName: ibm-monitoring-prometheusext-operator-app
