channels:
- currentCSV: ibm-monitoring-prometheus-operator-ext.v1.9.1
  name: stable-v1
- currentCSV: ibm-monitoring-prometheus-operator-ext.v1.9.1
  name: beta
- currentCSV: ibm-monitoring-prometheus-operator-ext.v1.9.1
  name: dev
defaultChannel: stable-v1
packageName: ibm-monitoring-prometheusext-operator-app
